import './scss/style.scss'
// import './section-header'
// import './section-banner'
// import './section-benefits'
// import './section-inspiration'
// import './section-perfection'
// import './section-toplist'
// import './section-video'
// import './section-footer'
import './section-signin'
import './section-signup'
import './js/script'